- hosts: localhost
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:
    - package:
        name: jq
        state: present
      become: yes

    - pip:
        name: ['setuptools_rust','msrest','azure-cli','ansible[azure]','azure-mgmt-monitor']