- hosts: localhost
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:
    - package:
        name: jq
        state: present
      become: yes

    - pip:
        name:
          - ansible[azure]>=2.0.0
          - msrest