- hosts: localhost
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:


    - debug:
        var: hostvars['localhost']

    - package:
        name: jq
        state: present
      become: yes

    - pip:
        name: ['ansible[azure]']