- hosts: localhost
  gather_facts: False
  
  tasks:
  - name: get local_user
    local_action: command whoami
    register: local_user

  - name: create dir
    file: 
        path: ~/.ssh
        state: directory 
        mode: 0700 
        owner: "{{local_user}}"
        
  - shell: echo {{ssh_private_key}} |base64 --decode
    register: ssh_private_key_decoded
  
  - name: Install ssh key
    copy: 
        content: "{{ ssh_private_key_decoded }}"
        dest: ~/ssh/id_rsa
        mode: 0600
        owner: "{{local_user}}"
