- hosts: localhost
  gather_facts: True
  
  vars:
    local_home: "{{ lookup('env','HOME') }}"
    local_user: "{{ lookup('env','USER') }}"  
  
  tasks:
  - name: create dir
    file: 
        path: ~/.ssh
        state: directory 
        mode: 0700 
        owner: "{{local_user}}"
        
  - shell: echo {{ssh_private_key}} |base64 --decode
    register: ssh_private_key_decoded
  
  - name: Install ssh key
    copy: 
        content: "{{ ssh_private_key_decoded }}"
        dest: ~/ssh/id_rsa
        mode: 0600
        owner: "{{local_user}}"
