---        
- hosts: kubectl_host
  tasks:   
    
    - name: Check for Python
      raw: test -e /usr/bin/python
      changed_when: false
      failed_when: false
      register: check_python    
      
    - name: Install Python
      raw: apt -y update && apt install -y python-minimal
      when: check_python.rc != 0    
      
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes   
        
    - name: Install required packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
        - ca-certificates
        - apt-transport-https
        - curl
        - gnupg2
        - software-properties-common       
        
                
        
    - name: Add the Kubernetes signing key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present   

    - name: Add kubernetes
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present           
        
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes       
        
    - name: Install required packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
        - kubectl
        
    - name: Create directory .kube
      file:
        path: $HOME/.kube
        state: directory
        recurse: yes         
        
   - name: Copy conf file from master
     synchronize: src=~/.kube/config dest=~/.kube/config
     delegate_to: master        
        
        

        

