---        
#- hosts: all
  #tasks:
  
    #- name: get IP geolocation data
      #ipinfoio_facts: 
      #register: ipdata    
  
- hosts: master
  tasks:   
  
    #- name: print IP
      #debug:
        ##var: "hostvars[\"{{ item }}\"]"
        #var: hostvars[inventory_hostname]['ansible_default_ipv4']['address']    
  
    - name: create namespaace 
      shell: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml
      
    - name: create services 
      shell: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml 
      
    - name: create secret
      shell: kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
      
      
    - name: Create dir 
      file:
        path: ~/metallb/
        state: directory   
      
    - name: Download ConfigMap.yaml
      get_url:
        url: https://raw.githubusercontent.com/QCDIS/k8s-resources/master/metallb/ConfigMap.yaml
        dest: ~/metallb/ConfigMap.yaml
      
    - name: Add IP
      lineinfile:
        path: ~/metallb/ConfigMap.yaml
        regexp: "      - IP_RANGE"
        line: "      - {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        
        
    - name: apply ConfigMap
      shell: kubectl apply -f ~/metallb/ConfigMap.yaml


