- hosts: all
  become: yes
  tasks:
  
    - name: Wait for automatic system updates
      shell: while sudo fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 3; done;
      with_items:
        - lock
        - lock-frontend
          
    - name: Check for Python
      raw: test -e /usr/bin/python
      changed_when: false
      failed_when: false
      register: check_python    
      
    - name: Install Python
      raw: apt -y update && apt install -y python-minimal
      when: check_python.rc != 0    
      
    - pip:
        name:
            - openshift==0.11.0
            - kubernetes==11.0.0      
      
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes      
        
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
      
    - name: Install required packages
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
        - nfs-kernel-server
        
        
    - name: Create dir 
      file:
        path: /mnt/kubedata/
        state: directory
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: 777 

        
    - name: Add a line to a file if the file does not exist, without passing regexp
      lineinfile:
        path: /etc/exports
        line: /mnt/kubedata/ 145.100.128.0/21(rw,sync,no_subtree_check,insecure)
        
    - name: Add a line to a file if the file does not exist, without passing regexp
      lineinfile:
        path: /etc/exports
        line: /mnt/kubedata/ 145.146.100.0/24(rw,sync,no_subtree_check,insecure)
        
    - name: exportfs
      shell: exportfs -rav
 
