- hosts: master
  gather_facts: False
  tasks:
  - name: 
    pause:
        seconds: 10

  - name: Verify
    shell: kubectl get nodes
    register: command_output
  
  - name:
    debug:
      msg: "{{ command_output.stdout }}"
