- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: install openstacksdk
      pip:
        name: openstacksdk

    - os_flavor_info:
      environment:
        OS_AUTH_URL: "https://host:35357/v3"
        OS_PROJECT_ID: "ID"
        OS_AUTH_TYPE: "v3oidcaccesstoken"
        OS_IDENTITY_PROVIDER: "egi.eu"
        OS_PROTOCOL: "openid"
        OS_ACCESS_TOKEN: "TOKEN"
      register: result


    - name: Echo my_env_var again
      shell: "echo $OS_AUTH_URL $OS_PROJECT_ID $OS_AUTH_TYPE $OS_IDENTITY_PROVIDER $OS_PROTOCOL $OS_ACCESS_TOKEN"

    - name: print result
      debug:
        var: result