- hosts: localhost
  tasks:
    - name: install openstacksdk
      pip:
          name:
            - openstacksdk >= 0.12.0
            - decorator


    - name: Authenticate to the cloud and retrieve the service catalog
      os_auth:
        cloud: rax-dfw

    - name: Show service catalog
      debug:
        var: service_catalog

