- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - pip:
        name: ['boto3', 'botocore']

    - ec2_ami_info:
        aws_access_key: "{{ ansible_env.AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ ansible_env.AWS_SECRET_KEY }}"
        region: "{{ ansible_env.REGION }}"
        filters:
          name: "ubuntu*"


      register: ec2_ami_info_output

    - debug:
        var: ec2_ami_info_output