- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - ec2_instance_info:
        aws_access_key: "{{ ansible_env.AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ ansible_env.AWS_SECRET_KEY }}"