---        
- hosts: localhost
  gather_facts: yes
  vars:
    docker_env_variables:  "{{ ansible_env.DOCKER_ENV_VARIABLES }}" 

  tasks:
    
    - name: Add vars to dummy host
      add_host:
        name:   "k8s_deploy_vars_holder"
        docker_env_variables:  "{{ ansible_env.DOCKER_ENV_VARIABLES }}" 
        
    - name: replace 
      set_fact:
        new__env_variables: "{{  docker_env_variables | regex_replace('map[', '') | | regex_replace(']', '')  }}"
        
    - debug:
        var:  new__env_variables
