---        
- hosts: localhost
  gather_facts: true

  tasks:

    - name: Add vars to dummy host
      add_host:
        name:   "k8s_deploy_vars_holder"
        docker_image:  "{{ ansible_env.DOCKER_IMAGE }}"   
        docker_service_name:  "{{ ansible_env.DOCKER_SERVICE_NAME }}"     
        container_port:  "{{ ansible_env.CONTAINER_PORT }}"    
        k8s_namespace:  "{{ ansible_env.K8s_NAMESPACE }}"    

- hosts: master
  gather_facts: true
  vars:
    k8s_state: present
    docker_image: "{{ hostvars['k8s_deploy_vars_holder']['docker_image'] }}"
    docker_service_name: "{{ hostvars['k8s_deploy_vars_holder']['docker_service_name'] }}"
    container_port: "{{ hostvars['k8s_deploy_vars_holder']['container_port'] }}"
    k8s_namespace: "{{ hostvars['k8s_deploy_vars_holder']['k8s_namespace'] }}"
  
  tasks:

    - name: Printing k8s vars
      debug:
        msg: "{{ item }}"    
      with_items:
        - "{{ docker_image }}"
        - "{{ docker_service_name }}"
        - "{{ container_port }}"
        - "{{ k8s_namespace }}"
        
       
       
    - pip:
        name:
            - openshift==0.11.0
            - kubernetes==11.0.0
            
            
    - name: Create a k8s namespace
      k8s:
        name: "{{ k8s_namespace }}"        
        api_version: v1
        kind: Namespace
        state: present            

    - name: Create deployment
      k8s:
        state: "{{k8s_state}}"
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            namespace: "{{ k8s_namespace }}"        
            annotations:
            labels:
              service: "{{ docker_service_name }}"
            name: "{{ docker_service_name }}"
          spec:
            selector:
              matchLabels:
                service: "{{ docker_service_name }}"
            replicas: 1
            template:
              metadata:
                labels:
                  service: "{{ docker_service_name }}"
              spec:
                containers:
                - image: "{{ docker_image }}"
                  name: "{{ docker_service_name }}"
                  imagePullPolicy: Always
                  ports:
                  - containerPort: "{{ container_port }}"


    - name: Create service
      k8s:
        state: "{{k8s_state}}"
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            namespace: "{{ k8s_namespace }}"        
            labels:
              service: "{{ docker_service_name }}"
            name: "{{ docker_service_name }}"
          spec:
            type: NodePort  
            ports:
            - port: "{{ container_port }}"
              protocol: TCP
              name: http
            selector:
              service: "{{ docker_service_name }}"

