apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: K8s_NAMESPACE
  labels:
    io.kompose.service: SERVICE_NAME
  name: SERVICE_NAME
spec:
  selector:
    matchLabels:
      io.kompose.service: SERVICE_NAME
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: SERVICE_NAME
    spec:
      containers:
      - env:
        - name: NAME
          value: VALUE
        image: DOCKER_IMAGE
        name: SERVICE_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: CONTAINER_PORT
