apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: K8s_NAMESPACE
  annotations:
  labels:
    service: SERVICE_NAME
  name: SERVICE_NAME
spec:
  selector:
    matchLabels:
      service: SERVICE_NAME
  replicas: 1
  template:
    metadata:
      labels:
        service: SERVICE_NAME
    spec:
      containers:
      - image: DOCKER_IMAGE
        name: SERVICE_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: CONTAINER_PORT
