---
- hosts: master
  gather_facts: no
  vars:
    k8s_state: present
    k8s_namespace: kubernetes-dashboard
    k8s_dashboard_installed: lookup('env', 'k8s_dashboard_installed')
  tasks:

    - pip:
        name:
            - openshift==0.11.0
            - kubernetes==11.0.0

    - community.kubernetes.k8s_cluster_info:
        register: api_status

    - debug:
        var: api_status
