    
---        
- hosts: localhost
  gather_facts: no

  tasks:
    - name: Add vars to dummy host
      add_host:
        name: "k8s_deploy_vars_holder" 
        k8s_namespace: "{{ ansible_env.K8s_NAMESPACE }}"   
        
- hosts: master
  gather_facts: no
  vars:
    k8s_namespace: "{{ hostvars['k8s_deploy_vars_holder']['k8s_namespace'] }}"
  
  tasks:   
    - pip:
        name:
            - openshift==0.11.0
            - kubernetes==11.0.0
    
    - name: Get a list of services
      k8s_info:
        kind: Service
        namespace: "{{ k8s_namespace }}"
      register: k8s_services
      
    - name: print k8s_secrets
      debug:
        var: k8s_services      
