---
- hosts: master
  gather_facts: no
  vars:
    k8s_state: present
    k8s_namespace: kubernetes-dashboard
    k8s_dashboard_installed: lookup('env', 'k8s_dashboard_installed')
  tasks:

    - shell: cat ${HOME}/.kube/config
      register: config_out

    - debug:
        var: config_out
