apiVersion: v1
kind: PersistentVolume
metadata:
  name: PV_NAME
  labels:
    type: local
    location: COORDINATES
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: HOST
    path: "/mnt/kubedata/"
