#           apiVersion: v1
#           kind: Service
#           metadata:
#             namespace: K8s_NAMESPACE
#             labels:
#               service: DOCKER_SERVICE_NAME
#             name: DOCKER_SERVICE_NAME
#           spec:
#             type: NodePort  
#             ports:
#             - port: CONTAINER_PORT
#               protocol: TCP
#               name: http
#             selector:
#               service: DOCKER_SERVICE_NAME
