apiVersion: v1
kind: Service
metadata:
  namespace: K8s_NAMESPACE
  labels:
    service: SERVICE_NAME
  name: SERVICE_NAME
spec:
  type: NodePort  
  ports:
  - port: CONTAINER_PORT
    protocol: TCP
    name: http
  selector:
    service: SERVICE_NAME
