- hosts: localhost
  vars:
    region: "{{ ansible_env.REGION }}"
    cidr_block:  "{{ ansible_env.CIDR_BLOCK }}"
    aws_access_key: "{{ ansible_env.AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ ansible_env.AWS_SECRET_KEY }}"

  tasks:
     - debug:
         var: region

     - debug:
         var: cidr_block

     - debug:
         var: aws_access_key

     - debug:
         var: aws_secret_key

     - ec2_vpc:
         aws_access_key: "{{ aws_access_key }}"
         aws_secret_key: "{{ aws_access_key }}"
         state: present
         cidr_block: "{{ cidr_block }}"
         resource_tags: { "Environment":"Development" }
         region: "{{ region }}"

