- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    region: "{{ ansible_env.REGION }}"
    cidr_block: "{{ ansible_env.CIDR_BLOCK }}"
    aws_access_key: "{{ ansible_env.AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ ansible_env.AWS_SECRET_KEY }}"
    vpc_name: "{{ ansible_env.VPC_NAME }}"

  tasks:
    - pip:
        name: botocore

    - name: ec2_vpc_net
      ec2_vpc_net:
         aws_access_key: "{{ aws_access_key }}"
         aws_secret_key: "{{ aws_secret_key }}"
         state: absent
         name: "{{ vpc_name }}"
#         cidr_block: "{{ cidr_block }}"
#         region: "{{ region }}"
         #         when: ansible_version.full <= "2.10"
      register: delete_vpc


    - debug:
         msg: "{{ delete_vpc.vpc }}"



