- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - import_tasks: 2.9/vm.yaml
      vars:
        region: "{{ ansible_env.REGION }}"
        aws_access_key: "{{ ansible_env.AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ ansible_env.AWS_SECRET_KEY }}"
        key_name: "{{ ansible_env.KEY_NAME}}"
        instance_type: "{{ ansible_env.INSTANCE_TYPE }}"
        image: "{{ ansible_env.AMI_ID }}"
        wait: Yes
        count: "{{ ansible_env.INSTANCE_COUNT }}"
        vpc_subnet_id: "{{ ansible_env.VPC_SUBNET_ID }}"
        assign_public_ip: "{{ ansible_env.INSTANCE_ASSIGN_PUBLIC_IP }}"
        state: present
        debug: false

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: "{{ ec2_output.instances }}"

    - debug:
        var: ec2_output

#    - ec2_vol:
#        instance: "{{ item.id }}"
#        volume_size: "{{ ansible_env.VOLUME_SIZE }}"
#      loop: "{{ ec2_output.instances }}"
#      register: ec2_vol_output
#
#    - debug:
#        var: ec2_vol_output


