- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    instance_ids: "{{ ansible_env.INSTANCE_IDS.split(',') }}"
  tasks:

    - ec2:
        region: "{{ ansible_env.REGION }}"
        aws_access_key: "{{ ansible_env.AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ ansible_env.AWS_SECRET_KEY }}"
        instance_ids: " {{ instance_ids }}"
        state: absent
      register: ec2_output


    - debug:
        var: ec2_output
