- hosts: all
  become: yes
  tasks:
    - name: install docker-py
      pip: 
        name: docker
  
    - name: Prune everything
      docker_prune:
        containers: yes
        images: yes
        networks: yes
        volumes: yes
        builder_cache: yes
        
        
    - name: Prune everything from shell
      shell: docker system prune --all -f

    - name: Prune everything from shell
      shell: docker container prune
        
    - name: Prune everything from shell
      shell: docker volume prune

    - name: list images
      shell: "docker images"
      register: images
      
      
    - name: print images
      debug:
        var: images      
