- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - import_tasks: 2.9/ec2_key.yaml
      vars:
        aws_access_key: "{{ ansible_env.AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ ansible_env.AWS_SECRET_KEY }}"
        key_name: "{{ ansible_env.KEY_NAME}}"
        region: "{{ ansible_env.REGION }}"
        state: present
        debug: false
