- hosts: localhost
  vars:
    - auth_data: {
       'auth_url': "{{ ansible_env.OS_AUTH_URL }}",
       'os_access_token': "{{ ansible_env.OS_ACCESS_TOKEN }}",
       'os_project_id': "{{ ansible_env.OS_PROJECT_ID }}",
       'os_auth_type': "{{ ansible_env.OS_AUTH_TYPE }}",
       'os_identity_provider': "{{ ansible_env.OS_IDENTITY_PROVIDER}}",
       'os_protocol': "{{ ansible_env.OS_PROTOCOL}}"
      }
      ansible_python_interpreter: /usr/bin/python3
    
  tasks:

#     - debug:
#         var: hostvars['localhost']['os'].split()[1]
                
    - os_image_info:
        properties:
          os_distro: "{{ hostvars['localhost']['os'].split()[0] | lower}}"
          os_version: "{{ hostvars['localhost']['os'].split()[1] | lower}}"
      register: image_info_output
      environment:
        OS_AUTH_URL: "{{ hostvars['localhost']['auth']['auth_url'] }}"
        OS_ACCESS_TOKEN: "{{ hostvars['localhost']['auth']['token'] }}"
        OS_PROJECT_ID: "{{ hostvars['localhost']['auth']['project_id'] }}"
        OS_AUTH_TYPE: "{{ hostvars['localhost']['auth']['token_type'] }}"
        OS_IDENTITY_PROVIDER: "{{ hostvars['localhost']['auth']['identity_provider'] }}"
        OS_PROTOCOL: "{{ hostvars['localhost']['auth']['protocol'] }}"

    - debug:
        var: image_info_output['openstack_image'][0]['id']

    - set_stats:
        data:
          image_id: "{{ image_info_output['openstack_image'][0]['id'] }}"
      register: set_stats_output

    - debug:
        var: set_stats_output

