- hosts: localhost
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:

    - local_action: copy content={{ item.value }} dest=/tmp/{{ item.name }}.json
      with_items:
        - { name: ssh_keys, value: "{{ ssh_keys }}" }
        - { name: os_server_output, value: "{{ os_server_output }}" }

    - shell: jq -s '.[0] * .[1]' /tmp/ssh_keys.json  /tmp/os_server_output.json > /tmp/attributes.json

    - include_vars:
        file: /tmp/attributes.json
        name: attributes

    - set_stats:
        data: "{{ attributes }}"
      register: attributes