- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: install openstacksdk
      pip:
        name: openstacksdk
        
#     - name: get vm flavors
#       os_flavor_info:
#       register: flavors

#     - name: print flavors
#       debug:
#         var: flavors

    - name: Retrieve all available images
      os_image_info:
      register: images

    - name: print images
      debug:
        var: images

#     - name: launch an instance
#       os_server:
#         state: present
#         name: "vm1"
#         availability_zone: "nova"
#         image: "b0049ae9-3090-4a76-b9da-c985409b3228"
#         key_name: "deleteme"
#         timeout: 200
#         flavor: "6e514065-9013-4ce1-908a-0dcc173125e4"

#    - name: remove an instance
#      os_server:
#        name: vm1
#        state: absent
