- hosts: localhost
  vars:
    - auth_data: {
       'auth_url': "{{ ansible_env.OS_AUTH_URL }}",
       'os_access_token': "{{ ansible_env.OS_ACCESS_TOKEN }}",
       'os_project_id': "{{ ansible_env.OS_PROJECT_ID }}",
       'os_auth_type': "{{ ansible_env.OS_AUTH_TYPE }}",
       'os_identity_provider': "{{ ansible_env.OS_IDENTITY_PROVIDER}}",
       'os_protocol': "{{ ansible_env.OS_PROTOCOL}}"
      }
      ansible_python_interpreter: /usr/bin/python3
      name: "vm1"
#      availability_zone: "nova"
      image: "{{ ansible_env.IMAGE_ID}}"
      key_name: "{{ ansible_env.KEY_NAME}}"
#      timeout: 200
      flavor: "{{ ansible_env.FLAVOR_ID}}"
#      network: "00129b7b-c6aa-4cef-822f-8793324a075e"
    
  tasks:
    - pip:
        name: 'openstacksdk'

    - os_flavor_info:
      register: flavors


    - debug:
        var: flavors

#    - name: Retrieve all available images
#      os_image_info:
#      register: images
#
#    - name: print images
#      debug:
#        var: images
#
    - name: launch an instance
      os_server:
        state: present
        name: "vm1"
#        availability_zone: "nova"
        image: "cb54f10d-7da0-4cc4-9887-72126e772761"
        key_name: "deleteme3"
        timeout: 200
        flavor: "6e514065-9013-4ce1-908a-0dcc173125e4"
        network: "00129b7b-c6aa-4cef-822f-8793324a075e"
#
#    - name: remove an instance
#      os_server:
#        name: vm1
#        state: absent
