- hosts: localhost
  vars:
    - auth_data: {
       'auth_url': "{{ ansible_env.OS_AUTH_URL }}",
       'os_access_token': "{{ ansible_env.OS_ACCESS_TOKEN }}",
       'os_project_id': "{{ ansible_env.OS_PROJECT_ID }}",
       'os_auth_type': "{{ ansible_env.OS_AUTH_TYPE }}",
       'os_identity_provider': "{{ ansible_env.OS_IDENTITY_PROVIDER}}",
       'os_protocol': "{{ ansible_env.OS_PROTOCOL}}"
      }
      ansible_python_interpreter: /usr/bin/python3

  tasks:
    - local_action: copy content={{ images }} dest=/tmp/images.json
    - local_action: copy content={{ selected_flavors }} dest=/tmp/selected_flavors.json
    - local_action: copy content={{ networks }} dest=/tmp/networks.json
    - local_action: copy content={{ ssh_keys }} dest=/tmp/ssh_keys.json

#    - include_tasks: 2.9/vm.yaml
#      vars:
#        state: present
#        name: "{{ item.key }}"
#        image: "{{ image_id }}"
#        key_name: "{{ key_name }}"
#        flavor: "{{ flavor_id }}"
#        network: "{{ network_id }}"
#        access_token: "{{ access_token }}"
#        protocol: openid
#        instance_name: "{{ item.key }}"
#      loop: "{{ hostvars['localhost']['instances'] | dict2items }}"

#    - debug:
#        var: os_server_output