- hosts: localhost
  vars:
    - auth_data: {
       'auth_url': "{{ ansible_env.OS_AUTH_URL }}",
       'os_access_token': "{{ ansible_env.OS_ACCESS_TOKEN }}",
       'os_project_id': "{{ ansible_env.OS_PROJECT_ID }}",
       'os_auth_type': "{{ ansible_env.OS_AUTH_TYPE }}",
       'os_identity_provider': "{{ ansible_env.OS_IDENTITY_PROVIDER}}",
       'os_protocol': "{{ ansible_env.OS_PROTOCOL}}"
      }
      ansible_python_interpreter: /usr/bin/python3

  tasks:
    - include_tasks: 2.9/vm.yaml
      vars:
        state: present
        name: "{{ hostvars['localhost']['instances'] }}"
        image: "{{ image_id }}"
        key_name: "{{ key_name }}"
        flavor: "{{ flavor_id }}"
        network: "{{ network_id }}"
        access_token: "{{ access_token }}"
      loop: "{{ hostvars['localhost']['instances'] }}"
#      loop_control:
#        loop_var: num_of_instances

    - debug:
        var: os_server_output