- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    auth_data: {
      'auth_url': "{{ ansible_env.OS_AUTH_URL }}",
      'os_access_token': "{{ ansible_env.OS_ACCESS_TOKEN }}",
      'os_project_id': "{{ ansible_env.OS_PROJECT_ID }}",
      'os_auth_type': "{{ ansible_env.OS_AUTH_TYPE }}",
      'os_identity_provider': "{{ ansible_env.OS_IDENTITY_PROVIDER}}",
      'os_protocol': "{{ ansible_env.OS_PROTOCOL}}"
    }
  tasks:
    - set_fact:
        random_key_name: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"

    - import_tasks: 2.9/os_key.yaml
      vars:
        state: present
        name: "sdia_{{ random_key_name }}"
        access_token: "{{ access_token }}"


    - local_action: copy content={{ key_output }} dest=/tmp/key_output.json

    - shell: jq -r '.key | { "{{ item.key }}" :{ key:{id:.id, private_key:.private_key, name:.name} }} ' /tmp/key_output.json
      loop: "{{ instances | dict2items }}"
      register: key


    - debug:
        var: key


#    - debug:
#        var: key_stats_output