- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    auth_data: {
      'auth_url': "{{ ansible_env.OS_AUTH_URL }}",
      'os_access_token': "{{ ansible_env.OS_ACCESS_TOKEN }}",
      'os_project_id': "{{ ansible_env.OS_PROJECT_ID }}",
      'os_auth_type': "{{ ansible_env.OS_AUTH_TYPE }}",
      'os_identity_provider': "{{ ansible_env.OS_IDENTITY_PROVIDER}}",
      'os_protocol': "{{ ansible_env.OS_PROTOCOL}}"
    }
  tasks:
    - import_tasks: 2.9/os_key.yaml
      vars:
        state: absent
        name: "{{ ansible_env.KEY_NAME }}"

    - debug:
        var: key_output