- hosts: localhost
  vars:
    - auth_data: {
       'auth_url': "{{ ansible_env.OS_AUTH_URL }}",
       'os_access_token': "{{ ansible_env.OS_ACCESS_TOKEN }}",
       'os_project_id': "{{ ansible_env.OS_PROJECT_ID }}",
       'os_auth_type': "{{ ansible_env.OS_AUTH_TYPE }}",
       'os_identity_provider': "{{ ansible_env.OS_IDENTITY_PROVIDER}}",
       'os_protocol': "{{ ansible_env.OS_PROTOCOL}}"
      }
      ansible_python_interpreter: /usr/bin/python3

  tasks:
    -  uri:
        url: {{hostvars['localhost']['auth']['auth_url']}}
        user: {{hostvars['localhost']['auth']['user']}}
        password: {{hostvars['localhost']['auth']['token']}}
        method: POST
        body: "{ client_id: {{hostvars['localhost']['auth']['user']}},
                  client_secret: {{hostvars['localhost']['auth']['token']}},
                  grant_type: {{hostvars['localhost']['auth']['token_type']}},
                  refresh_token: {{hostvars['localhost']['auth']['keys']['refresh_token']}},
                  scope: openid%20email%20profile }"
        force_basic_auth: yes
        status_code: 200
        body_format: json
        register: response

    - debug:
        var: response